export const INC_INGREDIENT = "INC_INGREDIENT";
export const DEC_INGREDIENT = "DEC_INGREDIENT";
export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED";

export const PURCHASE_BURGER_STARTED = " PURCHASE_BURGER_STARTED";
export const PURCHASE_BURGER = " PURCHASE_BURGER";
export const PURCHASE_BURGER_FAILED = " PURCHASE_BURGER_FAILED";
