export const INC_INGREDIENT = "INC_INGREDIENT";
export const DEC_INGREDIENT = "DEC_INGREDIENT";
export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED";

export const PURCHASE_BURGER_INIT = "PURCHASE_BURGER_INIT";
export const PURCHASE_BURGER_STARTED = "PURCHASE_BURGER_STARTED";
export const PURCHASE_BURGER = "PURCHASE_BURGER";
export const PURCHASE_BURGER_FAILED = "PURCHASE_BURGER_FAILED";

export const FETCH_ORDERS_STARTED = "FETCH_ORDERS_STARTED";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";

export const AUTH_STARTED = "AUTH_STARTED";
export const AUTH = "AUTH";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
